spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
    database: mysql

  datasource:
    url: jdbc:mysql://gogogo.ccszmnhxhmwx.ap-northeast-2.rds.amazonaws.com/gogogo_db
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
    

logging:
  level:
    org.hibernate.SQL: debug
